name: CD

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  APP_VERSION: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker image
        run: gradle publishImage

      - name: Update values.yaml
        run: |
          echo "FROM ${{ env.DOCKER_HUB_USERNAME }}/photo-album-ui:${{ env.APP_VERSION }}" > Dockerfile 
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add Dockerfile
          git commit -m "Update Dockerfile"
          git push

  openshift-webhook:
    runs-on: ubuntu-latest
    needs: [build-and-deploy]

    steps:
      - name: Invoke deployment hook for Akos
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL_AKOS }}
      - name: Invoke deployment hook for Geri
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL_GERI }}
